daemon:
  cwd: /var/run/sync-daemon
  timezone: Asia/Shanghai
  max_parallel: 10
  status_output: /srv/http/mirrorz.root/status.json
  secret: 01878661fbe191e149e0db99a476973e # openssl rand -hex 16

jobs: # default options for jobs
  config_dir: ./etc/jobs.conf.d
  cooldown: 10 # minutes
  url: /mirrors/%i/
  help: https://linux.xidian.edu.cn/git/xdlinux/mirror-help/src/branch/master/%i.md
